{{- if .Values.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "istio-sidecar-with-gatewayapi.fullname" . }}
  labels:
    {{- include "istio-sidecar-with-gatewayapi.labels" . | nindent 4 }}
spec:
  host: {{ default (include "istio-sidecar-with-gatewayapi.fullname" .) .Values.destinationRule.host }}
  {{- with .Values.destinationRule.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.destinationRule.subsets }}
  subsets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
