apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "istio-sidecar-with-gatewayapi.fullname" . }}-index
  labels:
    {{- include "istio-sidecar-with-gatewayapi.labels" . | nindent 4 }}
data:
  index.html: |-
{{ include "istio-sidecar-with-gatewayapi.indexPage" . | nindent 4 }}
