apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: gw-istio
spec:
  parentRefs:
  - name: istio-gw
    namespace: istio-system
  hostnames:
  - istio.example.com
  rules:
  - backendRefs:
    - name: echo
      port: 80
