{{- if .Values.gateway.enabled -}}
{{- $fullName := include "istio-ambient-with-gatewayapi.fullname" . -}}
{{- $defaultListener := dict "name" "http" "hostname" "example.com" "port" 80 "protocol" "HTTP" "allowedRoutes" (dict "namespaces" (dict "from" "Same")) -}}
{{- $listeners := .Values.gateway.listeners | default (list $defaultListener) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $fullName }}-gateway
  labels:
    {{- include "istio-ambient-with-gatewayapi.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName | default "istio" | quote }}
  listeners:
    {{- toYaml $listeners | nindent 4 }}
{{- end }}
