nameOverride: sample-was

podAnnotations:
  sidecar.istio.io/inject: "true"

web:
  indexPage:
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>sample-was</title>
      </head>
      <body>
        <main>
          <h1>sample-was</h1>
          <p>백엔드(Web Application Server) 역할을 가정한 Gateway API 샘플입니다.</p>
        </main>
      </body>
      </html>

httpRoute:
  hostnames:
    - sample-was.dongdorrong.com
