apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-route
  namespace: gw-cilium
spec:
  parentRefs:
  - name: cilium-gw
  hostnames:
  - cilium.example.com
  rules:
  - backendRefs:
    - name: echo
      port: 80
